creating an array using numpy

In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.size

4

In [ ]:
arr.ndim

1

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.array([100,78,65,45],dtype = 'int8')

In [ ]:
arr1 = np.array([1,2,3,4],dtype = "int8")

In [ ]:
arr1.dtype

dtype('int8')

creating matrix in numpy

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.size

6

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3.size

12

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
a = np.array(42) # 0-d, single int
a1 = np.array([42]) # 1-d
b = np.array([1,2,3,4,5]) # 1-d
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [ ]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


access element in arrays and matrics , similar to slicing

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0:2])

[1 2]


In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr2[0,1]) #2
print('5th element on 2nd row: ',arr2[1,4] ) # 10
print(arr2[1,0:3])# 2 row, first 3 elem

2nd element on 1st row:  2
5th element on 2nd row:  10
[6 7 8]


In [ ]:
arr3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2*2*3
print(arr3[0,1,2])

6


Slicing works in numpy array as well

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2]) # start: stop: step

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


slicing of 2-d, 3-d arrays

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2*5

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
arr[0:2,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[0:2,2])

[3 8]


In [ ]:
print()