In [2]:
import numpy as np
demo_matrix = np.array(([13,35,74,48], [23,37,37,38],[73,39,93,39]))


In [3]:
demo_matrix

array([[13, 35, 74, 48],
       [23, 37, 37, 38],
       [73, 39, 93, 39]])

In [4]:
demo_matrix[0:3, 1:3]


array([[35, 74],
       [37, 37],
       [39, 93]])

In [12]:
arr = [100,200,300,400,500,600,700,800,900,1000]
arr[0:7]
arr[0:7] = [5] * 7
arr


[5, 5, 5, 5, 5, 5, 5, 800, 900, 1000]

In [14]:
demo_array = np.arange(0,10)
demo_array

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [15]:
demo_array<3

array([ True,  True,  True, False, False, False, False, False, False,
       False])

In [16]:
import pandas as pd
flowers_list = pd.Series([1,2,3,4], index=['One','Two','Three','Flower'])


In [17]:
flowers_list['Three']

3

In [35]:
import pandas as pd

# Sample DataFrame
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

# Group by 'category' and count the number of customers in each category
category_counts = data_customer.groupby('category').size()
#data_customer(['category'])['customer'].value_counts()

print(category_counts)
#data_customer


category
cat1    1
cat2    2
cat3    1
dtype: int64


In [52]:
data_sales = pd.DataFrame({

          'sales_india_2023' : [100,200,300,400],
          'category' : ['cat2', 'cat3', 'cat3','cat4'],
          'year' : [2010,2020, 2021, 2024],
          'imp' : ['yes','yes','no', 'no']
})

In [53]:
data_sales

sales_india_2023 category  year  imp
0               100     cat2  2010  yes
1               200     cat3  2020  yes
2               300     cat3  2021   no
3               400     cat4  2024   no

In [59]:
data_sales = data_sales.groupby('category').sum('sales_india_2023')
data_sales

sales_india_2023  year
category                        
cat2                   100  2010
cat3                   500  4041
cat4                   400  2024

In [60]:
data_sales

sales_india_2023  year
category                        
cat2                   100  2010
cat3                   500  4041
cat4                   400  2024

In [41]:
df1 = data_customer.sort_values(by='sales',ascending=False)
df1

customer category important  sales
3       104     cat3       yes    663
2       103     cat1       yes    214
0       101     cat2       yes    123
1       102     cat2        no     52

In [29]:
data_customer['category']['customer'].value_counts()

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64

In [31]:
data_customer['category'].value_counts()

category
cat2    2
cat1    1
cat3    1
Name: count, dtype: int64

In [20]:
category_counts = data_customer.groupby('category').size()
print(category_counts)

category
cat1    1
cat2    2
cat3    1
dtype: int64


In [39]:
import pandas as pd

# Sample DataFrame
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

# Select the rows with index 1 and 2 and the columns 'customer' and 'sales'
result = data_customer.loc[1:2, ['customer', 'sales']]

print(result)


   customer  sales
1       102     52
2       103    214


In [45]:
import pandas as pd

# Sample DataFrame
data_customer = pd.DataFrame({
    'customer': [101, 102, 103, 104],
    'category': ['cat2', 'cat2', 'cat1', 'cat3'],
    'important': ['yes', 'no', 'yes', 'yes'],
    'sales': [123, 52, 214, 663]
})

# Select the rows with index 1 and 2 and the columns 'customer' and 'sales'
result = data_customer.loc[[1,2], [0,3]]


print(result)


KeyError: "None of [Index([0, 3], dtype='int64')] are in the [columns]"