creating an array using numpy

# New Section

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
a = "Data Science"
for i in range(0,5):
  print(a)

Data Science
Data Science
Data Science
Data Science
Data Science


In [ ]:
n = 8
for i in range(1, 11):
  print("{} ^ {} =".format(n, i), n**i)

8 ^ 1 = 8
8 ^ 2 = 64
8 ^ 3 = 512
8 ^ 4 = 4096
8 ^ 5 = 32768
8 ^ 6 = 262144
8 ^ 7 = 2097152
8 ^ 8 = 16777216
8 ^ 9 = 134217728
8 ^ 10 = 1073741824


In [ ]:
n = 10
i = 1
while i <= n:
  print(i)
  i = i +1

1
2
3
4
5
6
7
8
9
10


In [ ]:
for i in range(-10, -1, -1):
  print(i)

In [1]:
def function(var1=2, var2=4):
    var2 = 6
    var1 = 5
    print(var1, var2)

function(10, 20)

5 6


In [12]:
color = ['white','red', 'blue', 'green','blue','yellow', 'black']
color.pop(5)
color

['white', 'red', 'blue', 'green', 'blue', 'black']

In [9]:
alphabet = ['a','b','c']
for i in alphabet:
 print(i)
len(alphabet)

a
b
c


3

In [7]:
repeated_list = [2] * 4
print(repeated_list)

[2, 2, 2, 2]


In [3]:
class Person:
    def __init__(self, name, age):
        # Write your code below
        self.name = name
        self.age = age

# Create an object of the Person class
name = input()
age = int(input())
person = Person(name,age)

# Print the attributes of the person object
print(person.name)
print(person.age)

aks
14
aks
14


In [1]:
def my_function(a, b, **kwargs, *args):
    return a+b
my_function(5,6)

SyntaxError: invalid syntax (<ipython-input-1-4d53cb9e0e3c>, line 1)

In [ ]:
import random
random_val = random.randint(1,50)
random_val

41

In [ ]:
a = lambda x: x * x + 5
a = 1.8 * 20 + 32
print(a)

68.0


In [ ]:
a = 9
b = 5
a//b

1

In [ ]:
a = "I am a Data Scientist"
if "Data" in a:
 print("It is present")
else:
 print(False)

It is present


In [ ]:
import numpy as np

In [ ]:
arr = np.array([1,2,3,4])
print(arr)

[1 2 3 4]


In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.size

4

In [ ]:
arr.ndim

1

In [ ]:
arr.dtype

dtype('int64')

In [ ]:
arr1 = np.array([100,78,65,45],dtype = 'int8')

In [ ]:
arr1 = np.array([1,2,3,4],dtype = "int8")

In [ ]:
arr1.dtype

dtype('int8')

creating matrix in numpy

In [ ]:
arr2 = np.array([[1,2,3],[4,5,6]])

In [ ]:
print(arr2)

[[1 2 3]
 [4 5 6]]


In [ ]:
arr2.size

6

In [ ]:
arr2.ndim

2

In [ ]:
arr2.shape

(2, 3)

In [ ]:
arr3 = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

In [ ]:
print(arr3)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
arr3.size

12

In [ ]:
arr3.ndim

3

In [ ]:
arr3.shape

(2, 2, 3)

In [ ]:
a = np.array(42) # 0-d, single int
a1 = np.array([42]) # 1-d
b = np.array([1,2,3,4,5]) # 1-d
c = np.array([[1,2,3],[4,5,6]])
d = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [ ]:
print(a.shape)
print(b.shape)
print(c.shape)
print(d.shape)

()
(5,)
(2, 3)
(2, 2, 3)


In [ ]:
print(a.size)
print(b.size)
print(c.size)
print(d.size)

1
5
6
12


access element in arrays and matrics , similar to slicing

In [ ]:
arr = np.array([1,2,3,4])
print(arr[0:2])

[1 2]


In [ ]:
arr2 = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print('2nd element on 1st row: ',arr2[0,1]) #2
print('5th element on 2nd row: ',arr2[1,4] ) # 10
print(arr2[1,0:3])# 2 row, first 3 elem

2nd element on 1st row:  2
5th element on 2nd row:  10
[6 7 8]


In [ ]:
arr3 =np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]]) #2*2*3
print(arr3[0,1,2])

6


Slicing works in numpy array as well

In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5])
print(arr[4:])
print(arr[:4])
print(arr[-3:-1])

[2 3 4 5]
[5 6 7]
[1 2 3 4]
[5 6]


In [ ]:
arr = np.array([1,2,3,4,5,6,7])
print(arr[1:5:2]) # start: stop: step

[2 4]


In [ ]:
print(arr[::2])

[1 3 5 7]


slicing of 2-d, 3-d arrays

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]]) # 2*5

In [ ]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10]])

In [ ]:
arr[0:2,2:5]

array([[ 3,  4,  5],
       [ 8,  9, 10]])

In [ ]:
print(arr[1, 1:4])

[7 8 9]


In [ ]:
print(arr[0:2,2])

[3 8]


In [ ]:
print()